import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const pdfService = {
    generateReport: (processedData, config, metadata) => {
        const doc = new jsPDF();
        const { teacher, className, subject } = metadata;

        doc.setFontSize(22);
        doc.text("Student Performance Report", 105, 20, { align: 'center' });

        doc.setFontSize(12);
        const dateStr = new Date().toLocaleDateString();
        doc.text(`Class: ${className}`, 20, 35);
        doc.text(`Subject: ${subject}`, 20, 42);
        doc.text(`Teacher: ${teacher}`, 20, 49);
        doc.text(`Generated: ${dateStr}`, 180, 35, { align: 'right' });

        // Prepare table data
        const tableHeaders = ['Student ID', 'Name', ...config.components.map(c => c.name), 'Total', 'Grade', 'Remark'];

        const tableData = processedData.map(student => {
            const row = [
                student['Student ID'],
                student['Student Name'],
                ...config.components.map(c => student[c.name] || '-'),
                student.totalScore,
                student.grade,
                student.remark
            ];
            return row;
        });

        autoTable(doc, {
            head: [tableHeaders],
            body: tableData,
            startY: 55,
            theme: 'grid',
            headStyles: { fillColor: [79, 70, 229] }, // Indigo-600
            styles: { fontSize: 10 },
            alternateRowStyles: { fillColor: [249, 250, 251] }
        });

        // Summary
        const finalY = doc.lastAutoTable.finalY || 60;
        doc.text(`Configuration: ${config.name}`, 20, finalY + 15);
        doc.setFontSize(10);
        doc.setTextColor(150);
        doc.text("Generated by Antigravity Exam System", 105, 280, { align: 'center' });

        doc.save(`Report_${className}_${subject}.pdf`);
    }
};
